### ISSUE TITLE
how to use definitions in a vmtree output

### ISSUE THREAD

**Issue by linuxcaffe** [hpincket/vimwiki-definitions-extractor#1]
So my starting point is https://github.com/vimwiki/utils/blob/master/vmtree.sh and because it's sort of my-taskwiki-specific thing, I'll hack on a fork here: https://github.com/linuxcaffe/utils.

My objective is to generate a linkified index of ~/.task/wiki/ that displays the Description:: definition. It might look like;

<pre>
= TaskWiki Index =
├── ~
├── area
│   ├── admin.area                   Administration area
│   ├── home.area                    Home improvement area
│   ├── index
│   └── it.area                      Information Technology area
├── context
├── index
├── project
│   ├── 4PetesSake.project           Pete's Sake band project
│   ├── 62Canoe.project              62Canoe-building project
│   ├── acct.project                 Accounting, Banking etc
</pre>

There are a few other things I would tweak, but getting these definitions going would be sweet!
any suggestions appreciated

**Comment by hpincket** [comment]
Hey, I'll try and get to this soon.

**Comment by hpincket** [comment]
So I don't think you'll need a whole lot of this script. Right now it concatenates all the files with tail and sed. You won't need either of those since you loop through all the files already. So on each file you'll want to use awk to find the first definition of 'Description'. Print that to a Bash variable, then exit early.

You won't need the DECK variable, as I used that to split the definition output.

The 'if' on line 34 signifies the end of a definition. You can change the if clause on line 35 to if(WORD == "Description") . If true, then print the DEF and make an early exit  0. You can do the same to the identical if/else statement starting on line 46.

So in the end your awk should be much simpler. Give it a shot and let me know, I don't mind helping out.

**Comment by linuxcaffe** [comment]
Awesome! that's VERY helpful! 
I've updated https://github.com/linuxcaffe/taskwiki-utils.git and those Descriptions will be the icing on the cake!

**Comment by hpincket** [comment]
Cool. I also use taskwarrior, but I've kept it separate from vimwiki. What's your goal for this sort of integration? and how does it compare to the vimwiki extension on taskwarrior's site?

**Comment by linuxcaffe** [comment]
I've updated gen-index and.. well. doesn't crash, but doesn't reveal any descriptions either :)

**Comment by linuxcaffe** [comment]
I'm using taskwiki, which uses vimwiki. I'm also using vim-template, and this gen-index is part of the glue to hold it all together.

https://github.com/tbabej/taskwiki
https://github.com/linuxcaffe/taskwiki-template

**Comment by linuxcaffe** [comment]
https://github.com/linuxcaffe/taskwiki-utils/blob/master/gen-index more clues please! :)
(link changed)

**Comment by hpincket** [comment]
Closing.

**Comment by linuxcaffe** [comment]
All good amigo, had some successes, which I will link, thanks

**Comment by hpincket** [comment]
I wait in anticipation.

**Comment by linuxcaffe** [comment]
and yer gonna like it!

not awk, grep, see line 23 of https://github.com/linuxcaffe/taskwiki-utils/blob/master/gen-index

I haven't figure out alignment, it's still kludgy, but the script works,, somehow..

**Comment by hpincket** [comment]
Nice nice, clever use of cut. But this should only work on single line definitions, correct?

**Comment by linuxcaffe** [comment]
that's true, it's only work on a single line def. 

Have you got ideas for how to align the descriptions? the concealed link text is messing me up if I try to insert tabs. see: http://picpaste.com/taskwiki-screenshot-index-iO8zQ058.png
